name: Rob Whyte
favicon: null
layout_spectrum: 0.06743
typography_spectrum: 0.7509
title: The ramblings of Rob
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7d7d7d'
    - '#b9b9b9'
    - '#e55c64'
  brandStrength: 0.23645225097425282
  lightness: 0.792675185482949
  saturation: 0.407422658521682
  rhythmicContrast: 0.8178855266887695
purpose: []
